'use strict';

const PG_REIBUN_TABLE = [
  ['function','function'],
  ['class','class'],
  ['while','while'],
  ['for','for'],
  ['import','import'],
  ['init','init'],
  ['input','input'],
  ['return','return'],
  ['int','int'],
  ['double','double'],
  ['true','true'],
  ['false','false'],
  ['count','count'],
  ['split','split'],
  ['array','array'],
  ['string','string'],
  ['number','number'],
  ['bool','bool'],
  ['shift','shift'],
  ['unshift','unshift'],
  ['push','push'],
  ['add','add'],
  ['remove','remove'],
  ['reduce','reduce'],
  ['filter','filter'],
  ['length','length'],
  ['map','map'],
  ['sort','sort'],
  ['value','value'],
  ['element','element'],
  ['event','event'],
  ['long','long'],
  ['large','large'],
  ['index','index'],
  ['current','current'],
  ['call','call'],
  ['delete','delete'],
  ['break','break'],
  ['const','const'],
  ['let','let'],
  ['var','var'], 
  ['switch','switch'],
  ['try','try'],
  ['catch','catch'],
  ['throw','throw'],
  ['with','with'],
  ['label','label'],
  ['public','public'],
  ['static','static'],
  ['commit','commit'],
  ['cache','cache'],
  ['null','null'],
  ['undefind','undefind'],
  ['error','error'],
  ['file','file'],
  ['echo','echo'],
  ['print','print'],
  ['printf','printf'],
  ['log','log'],
  ['check','check'],
  ['fetch','fetch'],
  ['auto','auto'],
  ['sudo','sudo'],
  ['create','create'],
  ['--version','--version'],
  ['clone','clone'],
  ['cat␣file','cat file'],
  ['master','master'],
  ['resolve','resolve'],
  ['reject','reject'],
  ['tag','tag'],
  ['text','text'],
  ['update','update'],
  ['post','post'],
  ['get','get'],
  ['include','include'],
  ['void','void'],
  ['if','if'],
  ['insert','insert'],
  ['float','float'],
  ['fn','fn'],
  ['else','else'],
  ['message','message'],
  ['enum','enum'],
  ['parse','parse'],
  ['address','address'],
  ['apply','apply'],
  ['iterator','iterator'],
  ['python','python'],
  ['pypy','pypy'],
  ['ruby','ruby'],
  ['rust','rust'],
  ['php','php'],
  ['c#','c#'],
  ['react','react'],
  ['java','java'],
  ['typescript','typescript'],
  ['perl','perl'],
  ['kotlin','kotlin'],
  ['go','go'],
  ['haskell','haskell'],
  ['dart','dart'],
  ['swift','swift'],
  ['lisp','lisp'],
  ['cd','cd'],
  ['chdir','chdir'],
  ['tree','tree'],
  ['type','type'],
  ['chcp','chcp'],
  ['cls','cls'],
  ['exit','exit'],
  ['copy','copy'],
  ['md','md'],
  ['mkdir','mkdir'],
  ['mv','mv'],
  ['config','config'],
  ['ping','ping'],
  ['touch','touch'],
  ['man','man'],
  ['which','which'],
  ['find','find'],
  ['cal','cal'],
  ['date','date'],
  ['pwd','pwd'],
  ['head','head'],
  ['tail','tail'],
  ['PATH','PATH'],
  ['local','local'],
  ['bash','bash'],
  ['shell','shell'],
  ['linux','linux'],
  ['node','node'],
  ['mysql','mysql'],
  ['template','template'],
  ['end','end'],
  ['assert','assert'],
  ['high','high'],
  ['low','low'],
  ['c+','c+'],
  ['c++','c++'],
  ['operator','operator'],
  ['noexcept','noexcept'],
  ['this','this'],
  ['size','size'],
  ['first','first'],
  ['last','last'],
  ['start','start'],
  ['func','func'],
  ['long␣long','long long'],
  ['assign','assign'],
  ['set','set'],
  ['digit','digit'],
  ['binary','binary'],
  ['hexadecimal','hexadecimal'],
  ['decimal','decimal'],
  ['big','big'],
  ['small','small'],
  ['query','query'],
  ['struct','struct'],
  ['replace','replace'],
  ['reset','reset'],
  ['max','max'],
  ['min','min'],
  ['new','new'],
  ['object','object'],
  ['out','out'],
  ['root','root'],
  ['search','search'],
  ['next','next'],
  ['goto','goto'],
  ['continue','continue'],
  ['git␣config␣--global','git config --global'],
  ['git␣init','git init'],
  ['git␣clone','git clone'],
  ['git␣status','git status'],
  ['git␣diff','git diff'],
  ['git␣add','git add'],
  ['git␣diff␣--staged','git diff --staged'],
  ['git␣reset','git reset'],
  ['git␣commit␣-m','git commit -m'],
  ['git␣branch','git branch'],
  ['git␣checkout','git checkout'],
  ['git␣merge','git merge'],
  ['git␣branch␣-d','git branch -d'],
  ['git␣rm','git rm'],
  ['git␣rm␣--cached','git rm --cached'],
  ['git␣mv','git mv'],
  ['git␣stash','git stash'],
  ['git␣stash␣pop','git stash pop'],
  ['git␣stash␣list','git stash list'],
  ['git␣stash␣drop','git stash drop'],
  ['git␣log','git log'],
  ['git␣log␣--follow','git log --follow'],
  ['git␣show','git show'],
  ['git␣reset␣--hard','git reset --hard'],
  ['git␣fetch','git fetch'],
  ['git␣merge','git merge'],
  ['git␣push','git push'],
  ['git␣pull','git pull']
];
